version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./src:/app  # monta o diretório do host como /app no container
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1